steps:
  # 1. GCS에서 설정 파일 및 데이터 다운로드
  # 빌드 전에 필요한 파일들을 GCS 버킷에서 소스 코드로 가져옵니다.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Downloading configuration and data from GCS..."
        
        # public/dump 디렉토리 생성 (Vite 정적 자산용)
        mkdir -p public/dump
        
        # src/shared/api 및 src/shared/config 폴더가 없으면 생성
        mkdir -p src/shared/api
        mkdir -p src/shared/config

        # GCS에서 파일 다운로드 (경로는 FSD 구조 및 GCS 핸들러 변경 사항 반영)
        gsutil cp gs://${_GCS_BUCKET}/src/shared/api/dataService.tsx ./src/shared/api/dataService.tsx
        gsutil cp gs://${_GCS_BUCKET}/src/shared/api/pdfService.tsx ./src/shared/api/pdfService.tsx
        gsutil cp gs://${_GCS_BUCKET}/src/shared/config/index.ts ./src/shared/config/index.ts
        gsutil cp gs://${_GCS_BUCKET}/.env ./.env
        
        # dump 폴더의 내용을 public/dump로 복사 (재귀적, 병렬)
        # GCS 핸들러 변경으로 public/dump/... 구조일 것으로 가정, 혹은 기존 dump/... 구조 유지 시 호환성 고려
        # 안전을 위해 dump/* 및 public/dump/* 모두 시도하거나, gcs_handler.py 업로드 방식(public/dump)에 맞춤
        gsutil -m cp -r gs://${_GCS_BUCKET}/public/dump/* ./public/dump/

  # 2. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dump-master-lab', '.']

  # 3. Docker 이미지 푸시 (Container Registry 또는 Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dump-master-lab']

  # 4. Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dump-master-lab-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dump-master-lab'
      - '--region'
      - 'asia-northeast3' # 서울 리전
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# 변수 (트리거 설정에서 오버라이드 가능)
substitutions:
  _GCS_BUCKET: '' # 빌드 트리거에서 설정 필요

options:
  logging: CLOUD_LOGGING_ONLY
